- name: "Install haproxy package"
  ansible.builtin.apt:
    name: "haproxy"
    state: "present"
    update_cache: "yes"

- name: "Create config file"
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"

- name: "Restart systemd service"
  ansible.builtin.systemd:
    name: haproxy
    state: restarted